# Generated by Django 6.1.1 on 2026-09-18 05:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course', models.CharField(blank=True, default='', max_length=120)),
                ('type', models.CharField(choices=[('TAREA', 'Tarea'), ('EXAMEN', 'Examen'), ('PROYECTO', 'Proyecto'), ('LECTURA', 'Lectura'), ('OTRO', 'Otro')], default='TAREA', max_length=20)),
                ('due_date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Nulo mientras no haya autenticación real (Sprint 0-1, US-11).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DailyCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit_hours', models.DecimalField(decimal_places=2, default=6, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_capacity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('target_date', models.DateField()),
                ('estimated_hours', models.DecimalField(decimal_places=2, help_text='Debe ser mayor a 0 (US-02, Escenario 2).', max_digits=5, validators=[django.core.validators.MinValueValidator(0.25)])),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('DONE', 'Hecha'), ('POSTPONED', 'Pospuesta')], default='PENDING', max_length=20)),
                ('postpone_note', models.TextField(blank=True, default='')),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='planner.activity')),
            ],
            options={
                'ordering': ['target_date', 'estimated_hours'],
            },
        ),
    ]
