# Generated by Django 6.0.3 on 2026-09-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
